version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Qwerty123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Qwerty123!' -d master -i /docker-entrypoint-initdb.d/init.sql
        wait
    networks:
      - app-network
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=orderservice-db-1;Database=OrderServiceDB;User=sa;Password=Qwerty123!;TrustServerCertificate=True;
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"     
      - "15672:15672"   
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
volumes:
  db_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge